spring.application.name=cs232-secondplace
server.port=8080
# DB Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AttendanceDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourStrong@Passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# TU REST API Configuration
tu.api.url=https://restapi.tu.ac.th/api/v1/auth/Ad/verify2
tu.api.key=TU79749c8b40ec7a19af4ac0512d6eb8a8ff717bf737acfa2c3fdcabcd88f1745163fda22699369b6b332ec47c01bcc171