spring.application.name=cs232-secondplace
server.port=8080

# DB Connection - RDS
spring.datasource.url=jdbc:sqlserver://attendance-db.cmojqkgsn8ll.us-east-1.rds.amazonaws.com:1433;databaseName=AttendanceDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=admin
spring.datasource.password=0993141109
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# TU API
tu.api.url=https://restapi.tu.ac.th/api/v1/auth/Ad/verify2
tu.api.key=TU7046ecb130c0baae5af6d9df0bef0ee07618e9d5362e0912e6308a9505f4d39424d3fe96e27facd342a45bb68f12c28e

# AWS chage key Restrat Lab ; Key in Lab Detail
aws.accessKey=
aws.secretKey=
aws.sessionToken=
aws.region=us-east-1
aws.s3.bucket=attendxfiles
aws.rekognition.collection=attendance-faces
# Upload limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB